### ISSUE TITLE
Implement HC Events Table

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-components#15]
We have to provide a table component that shows events relevant for the chosen study area. In the long term, it could replace the [current HC Table](https://github.com/clarity-h2020/table-components/issues/1).

Status:

- [ ] GUI implementation ("html wireframe") as React AJAX web Application following this [CSV Schema](https://github.com/clarity-h2020/csis/issues/57#issuecomment-499381015)
- [ ] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [ ] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data based on the example table content from the mock-up screens. The internal model should be identical to the JSON model implemented by EMIKAT REST API
- [ ] Query EMIKAT REST API and retrieve **all** events (Baseline  + all RCP/time combinations) and map to internal state model
- [ ] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

Basic flow:

- get meta information about EMIKAT REST API from Data Package (HC Resource) from cSIS REST API.
- query EMIKAT Rest API with study area bbox to retrieve a table representative events for this area (30 events: 3 baseline and 27 future).

Goal is to show to the user a list of rare / frequent / occasional events in relation to RCP and time period so that he can make an informed [choice](https://github.com/clarity-h2020/docker-drupal/issues/58) for a RCP/time period of interest for impact calculation and adaption calculation.

For the table layout we start wit a simple list following the CSV structure, possibly highlighting the 3 baseline events.

**Comment by p-a-s-c-a-l** [comment]
Is the EMIKAT Endpoint available?

**Comment by humerh** [comment]
Information available with:

https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_HAZARD_EVENTS_STUDY.2036/table/data?rownum=1000
