### ISSUE TITLE
Implement EE Table

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-components#3]
Status:

- [x] GUI implementation ("html wireframe") as React AJAX web Application following the respective [Product Mock-Ups](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP1%20CO-Creation%2FT1.3%20Climate%20Services%20Co-Creation%2FCSIS%20Product%20Mockups)
- [x] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [x] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data based on the example table content from the mock-up screens.
- [x] the table contains the content for DC1 Reference study (The content will be retrieved from the [table-state-rest-api](https://github.com/clarity-h2020/table-state-rest-api))
- [x] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

Implement the EE Table following ~the Mock-Up and~ the approach described [here](https://github.com/clarity-h2020/csis/issues/46#issue-390262842). 

### EE Table GUI

![grafik](https://user-images.githubusercontent.com/1788226/49885860-97034e00-fe38-11e8-9b24-3aca8cd150b2.png)

**Important Note:** The Mock-Up seems to be outdated. It seems that a [request for revision](http://repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS%20Product%20Mockups/CSIS%20Product%20Master_PLINIVS%20REV/CSIS%20Product%20Master%20v0.3.4%20-%20redesign%20proposal%20Denis_Refiz_Jan_11_REV%20Plinivs.pdf) wasn't taken into account. Furthermore, [future exposure scenarios](https://github.com/clarity-h2020/data-package/issues/2) as shown in the mock-up above are, if at all, expected to be supported in the expert workflow of [DC2](https://github.com/orgs/clarity-h2020/teams/dc2/) only and for sure not in [CSIS v1](https://github.com/clarity-h2020/table-components/milestone/1). Therefore we follow KISS and YAGNI and start with the following EE table example taken from [this excel sheet](//repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP1%20CO-Creation/T1.3%20Climate%20Services%20Co-Creation/CSIS%20Product%20Mockups/CSIS%20Product%20Master_PLINIVS%20REV/CLARITY%20tables_mod.xlsx).

![grafik](https://user-images.githubusercontent.com/1788226/49885399-6969d500-fe37-11e8-921b-4cda5fbb4013.png)

### HC Table state model

- column 1: Hazard is the hazard 'applicable' to the exposed element
- column 2: category to group several EE layers. Same categorisation as in the map-component and HC/HC-LE tables!
- column 3: the vulnerability class, but essentially that's the name of the EE layer. For each vulnerability class, there will be a separate layer. So column 2 and column 3 define also the hierarchy of the map layer widget for the EE step!
- column 4: absolute numerical value 
- column 5: the unit may become part of the class or name, respectively. (to be consistent with in the [HC table](https://github.com/clarity-h2020/table-components/issues/1) which lacks a unit column [good reasons](https://github.com/clarity-h2020/data-package/issues/8#issuecomment-444515812))

Currently, no realistic example data is available. Example layers however will be reported in [this issue](https://github.com/clarity-h2020/data-package/issues/10).

### Mapping Data Package to HC Table state model

Same approach as in  [Implement HC table](https://github.com/clarity-h2020/table-components/issues/1): 
1) Fetch Data Package Meta Data and build WCS requests, 
2) Fetch data for each relevant layer from WCS, aggregate and transform to JSON state model.

**Comment by therter** [comment]
@ghilbrae @luis-meteogrid: An example for the table state model:

```
{
    "data": [
        {
            "hazard": "HW,PF,FL",
            "elementAtRisk": "Population",
            "vulnerabilityClasses": "Age group 0-14",
            "values": "2",
            "unit": "pop/km2"
        },
        {
            "hazard": "HW,PF,FL",
            "elementAtRisk": "Population",
            "vulnerabilityClasses": "Age group 15-64",
            "values": "2.45",
            "unit": "pop/km2"
        },
        {
            "hazard": "HW,PF,FL",
            "elementAtRisk": "Population",
            "vulnerabilityClasses": ">65",
            "values": "3",
            "unit": "pop/km2"
        },
        {
            "hazard": "PF,FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClasses": "Continuous Residential (S.L. > 80%)",
            "values": "2.3",
            "unit": "m3/m2"
        },
        {
            "hazard": "PF,FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClasses": "Med-Hi Density Discontinuous Res. (30% < S.L. < 80%)",
            "values": "2.56",
            "unit": "m3/m2"
        },
        {
            "hazard": "PF,FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClasses": "Low Density Discontinuous Res. (S.L. < 30%)",
            "values": "1.3",
            "unit": "m3/m2"
        },
        {
            "hazard": "PF,FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClasses": "Non Residential",
            "values": "1.56",
            "unit": "m3/m2"
        },
        {
            "hazard": "PF,FL",
            "elementAtRisk": "Infrastructure",
            "vulnerabilityClasses": "Roads",
            "values": "2.34",
            "unit": "ml"
        },
        {
            "hazard": "PF,FL",
            "elementAtRisk": "Infrastructure",
            "vulnerabilityClasses": "Railways",
            "values": "3.98",
            "unit": "ml"
        }
    ]
}
```

**Comment by ghilbrae** [comment]
Same as on issue #1:

Do you mean that all this data will be available from the layers that are going to be uploaded to geoserver? Will there be other sources? Where will the Data Package Meta Data reside?

**Comment by p-a-s-c-a-l** [comment]
> Do you mean that all this data will be available from the layers that are going to be uploaded to geoserver?

I hope so. :). But I don't expect that the exposure layers will already contain the information related to hazards. I think this relationship can be made via the [Data Package Meta-Data](https://github.com/clarity-h2020/data-package/tree/master/docs) (correct? @maesbri ) which is stored in the Drupal System an can be obtained via the Drupal JSON API.

This data (but for all grid cells of the study area, not just aggregated for tabular visualisation) is also needed for [impact calculation](https://github.com/clarity-h2020/csis/issues/22). IMHO the relation between Hazard Type and Element at Risk Type is also part of the [EMIKAT Logical Model](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP4%20Technology%20Support%2FT4.2%20Catalogue%20of%20Elements%20at%20Risk%20and%20Adaptation%20Options%2FImpact%20Calculation) (IMACT_CASE) (correct? @humerh). But I'm not sure whether we can query EMIKAT for this data.

**Comment by therter** [comment]
current status:

- [x] GUI implementation ("html wireframe") as React AJAX web Application following the respective [Product Mock-Ups](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP1%20CO-Creation%2FT1.3%20Climate%20Services%20Co-Creation%2FCSIS%20Product%20Mockups)
- [x] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [x] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data based on the example table content from the mock-up screens.
- [x] the table contains the content for DC1 Reference study
- [x] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

**Comment by ghilbrae** [comment]
Sorry for the radio silence.

We are still a bit confused about what it is expected from our side. So I will try to explain what we have understood and what questions we have so you can clarify anything:

* The idea is to have some kind of tool (API?) that queries the layers available in geoserver to return a JSON response with the data needed.
* The tool will be called by some module of the CSIS with the set of parameters/data/whatever that is needed according to the example above.
* The tool will return the information needed back.
* We will probably implement this using python or some python-related framework.
* Where is this tool supposed to be installed?
* How will authentication work?

**Comment by therter** [comment]
The example request of the [table-state-rest-api](https://github.com/clarity-h2020/table-state-rest-api/issues/1) is now used

**Comment by p-a-s-c-a-l** [comment]
Currently, the URL to the [table-state-rest-api](https://github.com/clarity-h2020/table-state-rest-api) is hard-coded. How can this work for different exposure resources? Why is this not loaded from the Data Package? The URl of the REST API should be stored in the EE Resource in the [corresponding Data Package](https://github.com/clarity-h2020/data-package/issues/10). We can use the new [references](https://github.com/clarity-h2020/csis/issues/58#issuecomment-506666707) field and URL of type `@tableview:meteogrid:rest` analogous to the `@mapview:ogc:wms` type [used](https://github.com/clarity-h2020/map-component/issues/29) by the Map Component. See also https://github.com/clarity-h2020/table-components/issues/16

Furthermore, we  have to switch to EMIKAT API as it supports Exposure Data for whole Europe.  See also https://github.com/clarity-h2020/table-state-rest-api/issues/3

**Comment by p-a-s-c-a-l** [comment]
@therter Is the bbox hardcoded, too? Will this table work for the cities of Alba Iulia, Agios Dimitrios and Bottrop ?

**Comment by therter** [comment]
> Is the bbox hardcoded, too? Will this table work for the cities of Alba Iulia, Agios Dimitrios and Bottrop ?

The table reads the bbox and the layers from the study. But the layers must be hosted by the meteogrid wms and contain the data for the cities of Alba Iulia, Agios Dimitrios and Bottrop. I don't know if there are still exposure layers available from the meteogrid wms.

**Comment by p-a-s-c-a-l** [comment]
Any news on that? Please explain how and where the correct exposure layer used by the table rest API is set. It's [not in the data package](https://github.com/clarity-h2020/csis/issues/15#issuecomment-528234819) so I assume it is hardcoded. Where? in the table or the API?

**Comment by p-a-s-c-a-l** [comment]
This table is obsolete now and won't be updated. See https://github.com/clarity-h2020/csis/issues/15#issuecomment-528248023
