### ISSUE TITLE
Implement RA/IA Table

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-components#4]
Status:

- [x] GUI implementation ("html wireframe") as React AJAX web Application following the respective [Product Mock-Ups](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP1%20CO-Creation%2FT1.3%20Climate%20Services%20Co-Creation%2FCSIS%20Product%20Mockups)
- [x] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [x] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data from the EMICAT Rest Interface 
- [x] the table contains the content for DC1 Reference study (The content will be retrieved from the emicat server). When this server contains the content  for DC1 Reference study, the table will also contain this content
- [ ] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

Implement the GUI following the description in [this issue]() and the approach described [here](https://github.com/clarity-h2020/csis/issues/46#issue-390262842). 

### RA/IA Table GUI

The table shows the output of the [impact model calculation](https://github.com/clarity-h2020/csis/issues/22). **Note:** The Mock-Ups aren't valid any more (see also https://github.com/clarity-h2020/csis/issues/45#issuecomment-448513587):

**Outdated Mock-Up**
![grafik](https://user-images.githubusercontent.com/1788226/50208724-42009400-0372-11e9-9ba5-d31fd6dfa9b2.png)

**Actual Mock-Up**: The table should look like this:

![grafik](https://user-images.githubusercontent.com/1788226/50208290-1cbf5600-0371-11e9-9b90-f34c5fba4d35.png)

### RA/IA Table state model

- Column 1: Hazard 
- Column 2: Exposure (Element at Risk) *grouped by Hazard*. e.g. **H**eat **W**ave has no impact on buildings or infrastructure, therefore there is no HW/Buildings Group.
- Column 3: The Vulnerability Classes of the respective Element at Risk
- Column 4: Unit
- Column 5-8: number of elements at risk impacted by hazard and grouped by damage classification D1 - D4 (see [legend](https://user-images.githubusercontent.com/1788226/48842709-3af75d80-ed95-11e8-8858-d3727a40a0e3.png))

### Mapping Data Package to HC Table state model
The Impact is calculated by the Risk & Impact Calculation Service (EMIKAT), therefore the data for the table should be retrieved from the [EMIKAT REST Service](https://service.emikat.at/EmiKat/swagger/index.html). Ideally, the JSON data obtained from EMIKAT matches directly the internal state model of the RA/IA Table. To be discussed with @bernhardsk and @humerh 
The REST URI can be obtained from the *path* property of respective RA/IA Data Resource of the Data Package. **However**, since the table data is rather small, the JSON could be stored directly in the *data* property of the Data Resource.

**Comment by therter** [comment]
@humerh @bernhardsk : An example for the table state model:

```
{
    "data": [
        {
            "hazard": "HW",
            "elementAtRisk": "Population",
            "vulnerabilityClass": "Age group 0-14",
            "unit": "pop/km2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "HW",
            "elementAtRisk": "Population",
            "vulnerabilityClass": "Age group 15-64",
            "unit": "pop/km2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "HW",
            "elementAtRisk": "Population",
            "vulnerabilityClass": ">65",
            "unit": "pop/km2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Population",
            "vulnerabilityClass": "Age group 0-14",
            "unit": "pop/km2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Population",
            "vulnerabilityClass": "Age group 15-64",
            "unit": "pop/km2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Population",
            "vulnerabilityClass": ">65",
            "unit": "pop/km2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClass": "Continuous Residential (S.L. > 80%)",
            "unit": "m3/m2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClass": "Med-Hi Density Discontinuous Res. (30% < S.L. < 80%)",
            "unit": "m3/m2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClass": "Low Density Discontinuous Res. (S.L. < 30%)",
            "unit": "m3/m2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Buildings",
            "vulnerabilityClass": "Non Residential",
            "unit": "m3/m2",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Infrastructure",
            "vulnerabilityClass": "Roads",
            "unit": "ml",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        },
        {
            "hazard": "FL",
            "elementAtRisk": "Infrastructure",
            "vulnerabilityClass": "Railways",
            "unit": "ml",
            "damageLevel1P": "1",
            "damageLevel2P": "3",
            "damageLevel3P": "2",
            "damageLevel4P": "3",
            "damageLevel5P": "5",
            "damageLevel6P": "7"
        }
    ]
}
```

**Comment by bernhardsk** [comment]
Progress update by @bernhardsk (AIT) and @humerh (AIT):

A first version of the Impact Calculation Module has been implemented in AIT EMIKAT. 
Impact was calculated for Hazard Index Type "heat-wave:consecutive-summer-days" using example data and based on the impact model descriptions provided by PLINIVS. 

As described above, the RA/IA Table should look like this: 
![grafik](https://user-images.githubusercontent.com/42140898/51693543-774a7280-1fff-11e9-9ce5-4c002b357ad7.png)

In order to provide the values required by the RA/IA table as shown above, a view has been created in EMIKAT to aggregate the results from the impact calculation, which currently looks like this: 
View (as Table): Damage level of Elements at Risk of each Vulnerability Class for a specific Impact Scenario/Hazard Index (without listing IDs):
![grafik](https://user-images.githubusercontent.com/42140898/51694397-0441fb80-2001-11e9-91ca-592cd6001412.png)

However the discussions during the CLARITY Developers/co-creation meeting in Vienna showed that the impact modelling should be changed slightly. The following changes should be carried out: 
1) The impact calculation has to focus on 1 specific hazard event at a time (e.g. for heat wave: 6 consecutive days over 30°C max). Therefore it makes no sense to include information about the time period and the emissions scenario (rcp). 
2) As input for the hazard event data, the impact calculation should use the Hazard-Local Effect layer/data. 
3) The way how the vulnerability functions/tables are taken into account should be changed (due to the changes in bulletpoint "1)").  

Next steps will focus on 
1) correcting the impact calculation as described above and changing the RA/IA table view accordingly.
2) connecting EMIKAT with the front-end in order to exchange the neccessary data to be shown to users in the front-end RA/IA table. As for the next steps, only impact will be calculated and show. Risk will follow at a later stage.  
3) implementing another example scenario (e.g. pluvial flood) using already available or otherwise dummy data.

**Comment by therter** [comment]
@bernhardsk @humerh 
I assume that Emicat (with the url https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_VULNERABILITY_FUNC.1837/table/data) should be used to get the data for the table. Do I understand correctly that the hazard and the element at risk can be extracted from the field "impact case" and which value of the field "Damage Level x" should be shown in the D1...D6 columns of the table or should all values be shown?

**Comment by therter** [comment]
current status:

- [x] GUI implementation ("html wireframe") as React AJAX web Application following the respective [Product Mock-Ups](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP1%20CO-Creation%2FT1.3%20Climate%20Services%20Co-Creation%2FCSIS%20Product%20Mockups)
- [x] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [x] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data from the EMICAT Rest Interface 
- [x] the table contains the content for DC1 Reference study (The content will be retrieved from the emicat server). When this server contains the content  for DC1 Reference study, the table will also contain this content
- [ ] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

**Comment by p-a-s-c-a-l** [comment]
The respective [Exposure Data Package](https://github.com/clarity-h2020/data-package/issues/16) has to be updated and .

**Comment by p-a-s-c-a-l** [comment]
@therter [Table](https://csis.myclimateservice.eu/node/22) broken due to changes in [EMIKAT RA/API](https://github.com/clarity-h2020/emikat/issues/9#issuecomment-525320830) data format.

We will update the table once this has stabilised.

**Comment by p-a-s-c-a-l** [comment]
Additional query parameters to be supported. See https://github.com/clarity-h2020/data-package/issues/42#
