### ISSUE TITLE
Implement AA Table

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-components#6]
Status:

- [x] GUI implementation ("html wireframe") as React AJAX web Application following the respective [Product Mock-Ups](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP1%20CO-Creation%2FT1.3%20Climate%20Services%20Co-Creation%2FCSIS%20Product%20Mockups)
- [x] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [x] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data based on the [json file](https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/data/adaptation-options/adaptation-options.json)
- [x] the table contains the content for DC1 Reference study
- [x] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

Implement the Adaptation Options Table

![grafik](https://user-images.githubusercontent.com/1788226/52196835-8f22c180-285d-11e9-8501-1c6c6c1ad87d.png)

Adaptation Options Data from Data Package: https://github.com/clarity-h2020/csis/issues/19#issuecomment-457556795

[Adaptation Measures Parameters v2.xlsx](https://github.com/clarity-h2020/table-components/files/2827026/Adaptation.Measures.Parameters.v2.Denis.xlsx)

**Comment by maesbri** [comment]
ok, I will update the json file describing the adaptation options accordingly.

**Comment by therter** [comment]
current status:

- [x] GUI implementation ("html wireframe") as React AJAX web Application following the respective [Product Mock-Ups](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP1%20CO-Creation%2FT1.3%20Climate%20Services%20Co-Creation%2FCSIS%20Product%20Mockups)
- [x] [Integration](https://github.com/clarity-h2020/docker-drupal/issues/11) into the respective [GL-Step](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields) as [External ReactMount Application](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/)
- [x] Design of a simplified internal state data model in JSON (the "table model") and definition of static JSON constants ([example](https://jsfiddle.net/helllth/f8be8ft8/113/)) as initial reference / example data based on the [json file](https://github.com/clarity-h2020/data-package/blob/master/examples/dc1-naples/data/adaptation-options/adaptation-options.json)
- [x] the table contains the content for DC1 Reference study
- [x] Mapping of the actual Data Package [Data Model](https://clarity-h2020.github.io/data-package/) to the internal JSON state data model with help of the [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43) and/or [REST Views](https://github.com/clarity-h2020/map-component/issues/2#issuecomment-445821280) and additional REST Micro Services for simple data aggregation and transformation.

**Comment by maesbri** [comment]
I was about to update the adaptation-options json file with the new information provided in the v2 of the excel file. However, the "targeted element at risk" column is almost empty. Should I assume that all adaptation option measures apply to buildings? (although in my opinion, some  of the ones related to the pavement/ground could be of application to roads too...).

btw, does any one know what is the original source of information of this? I could add it in the source section of the resource if we have the link.

**Comment by maesbri** [comment]
I don't know why this issue was closed when I added my last comment ...

**Comment by maesbri** [comment]
adaptation-options.json has been added as resource to the Naples data package (https://csis.myclimateservice.eu/node/221).

Bear in mind that the adaptation-options file is not complete as there is missing information in the excel file.

**Comment by p-a-s-c-a-l** [comment]
Adaptation Options JSON is loaded from GithHub, but Data Package Resource Meta-Data is [not yet available](https://github.com/clarity-h2020/data-package/issues/17). Furthermore, the `path` property changed to `path[]`!

On the other hand , there is now a [list of Adaptation Options](https://csis.myclimateservice.eu/adaptation-options-overview) in CSIS, so the usefulness of this table is questionable.

**Comment by p-a-s-c-a-l** [comment]
We don't need this table any more.
